development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  sorcery_twitter_callback_url: <%= ENV["SORCERY_TWITTER_CALLBACK_URL"] %>
  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>

  aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
  aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
  region: ENV["AWS_S3_REGION"]

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

  aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
  aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
  region: ENV["AWS_S3_REGION"]

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  sorcery_twitter_callback_url: <%= ENV["CALLBACK_URL"] %>
  sorcery_twitter_key: <%= ENV["SORCERY_TWITTER_KEY"] %>
  sorcery_twitter_secret: <%= ENV["SORCERY_TWITTER_SECRET"] %>

  sorcery_github_callback_url: <%= ENV["CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

  aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
  aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
  region: ENV["AWS_S3_REGION"]